# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c171ce5adb49cb678db3fe7449196605a0c480dc0c13c4d50f0d01c2c70e899fc74c7de542ddfcaaacbe94bf4ecbe61b0522e0a1050bfa6996ccdc9b3a1a07e1

test:
  secret_key_base: 341686eb78c6d505b7727747a65ccea8deb47091f73bde4d429ed951347eeffdf4bf6a96a35ad0c57127ba112086b10001a19ea7b040c7f89b9a23904de2f5fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
